### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by selyakovadim** [skodnik/Lamoda-PHP-Quest#2]
Привет!

**Comment by selyakovadim** [comment]
Вы зачем в одну миграцию запихнули создание 3х разных таблиц?

**Comment by selyakovadim** [comment]
Если вы пишете API, то зачем роуты положили в web.php, когда есть api.php специально для этого?

**Comment by selyakovadim** [comment]
Почему есть метод API для получения одного контейнера, но нет метода для получения всех контейнеров как было написано в условиях задачи?

**Comment by selyakovadim** [comment]
Вот это для чего написано, если по-умолчанию Фреймворк отдаст 404 страницу?
https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/routes/web.php#L27

**Comment by selyakovadim** [comment]
Что это? Вы случаем PHP и Python не перепутали?
https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/database/factories/container.php#L10

**Comment by selyakovadim** [comment]
`Т.к. текст задания можно понять неоднозначно, альтернативное, вероятно более верное решение в ветке`

Вы еще 10 решений напишите. Думаете их кто-нибудь будет смотреть? Что значит задание можно понять неоднозначно?

**Comment by selyakovadim** [comment]
Зачем контейнерам даете женские имена?)
https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/database/factories/container.php#L11

**Comment by skodnik** [comment]
> Привет!

Привет! Учитывая предыдущий опыт спрошу: - Вы представитель организаторов?

> Вы зачем в одну миграцию запихнули создание 3х разных таблиц?

Резонно, верну к стандартной практике. Спасибо! На этапе формирования кода это было удобно для меня.


> Почему есть метод API для получения одного контейнера, но нет метода для получения всех контейнеров как было написано в условиях задачи?

Ну как же, есть.

> Вот это для чего написано, если по-умолчанию Фреймворк отдаст 404 страницу?
> https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/routes/web.php#L27

Отдаст 405. Это стоит убрать. Обычно, ставлю todo для критичных мест и перед публикацией прохожусь по ним. Это место не критично, но, согласен, избыточно.

> Что это? Вы случаем PHP и Python не перепутали?
> https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/database/factories/container.php#L10

Это вариант генерации псевдослучайного идентификатора, т.к. на реальном примере, идентификаторы контейнеров и товаров не будут укладываться в автоинкрементируемые поля. И сюда стоит добавить проверку на дубликат, но это уже тонкости.

> `Т.к. текст задания можно понять неоднозначно, альтернативное, вероятно более верное решение в ветке`
> 
> Вы еще 10 решений напишите. Думаете их кто-нибудь будет смотреть? Что значит задание можно понять неоднозначно?

Судя по этому вопросу, Вы не представитель организатора. Читая текст задания можно решить что 100 товаров уникальны, а остальные 9900 нет, или что ассортимент состоит из всего 100 наименований товаров, а сам товар не уникален. Я, если увижу еще какой вариант, и сочту его вероятным, могу написать еще реализацию. Мне нравится.

> Зачем контейнерам даете женские имена?)
> https://github.com/skodnik/Lamoda-PHP-Quest/blob/c5baf68356d9deb35c812249340d4275425a6ee5/database/factories/container.php#L11

Это как в старом анекдоте - Во первых, это красиво!

Большое спасибо за комментарии!

**Comment by selyakovadim** [comment]
> Вы представитель организаторов?

Я не представитель организаторов и им не назывался. 

> Ну как же, есть.

Я вижу только метод для получения контейнеров с уникальными продуктами. Метода для получения всех контейнеров я не вижу.

> Это вариант генерации псевдослучайного идентификатора..

Тут вопрос не в том, что это делает, а в том, что зачем внутри вызова метода определяются две переменные min & max?

> Читая текст задания можно решить что 100 товаров уникальны, а остальные 9900 нет, или что ассортимент состоит из всего 100 наименований товаров, а сам товар не уникален

Не совсем понимаю в чем разница между этими двумя трактовками. Вы слишком усложняете. Есть 100 уникальных товаров, по 10 штук этих товаров лежит в 1000 ящиках в случайном порядке. То есть у нас есть 10000 товаров из этих 100 уникальных.

**Comment by skodnik** [comment]
> Я вижу только метод для получения контейнеров с уникальными продуктами. 

Так это и нужно. Из задания: "_Нужно вернуть список контейнеров, которые содержат все 100 уникальных товаров хотя бы по одному._", если я верно понимаю, это расширенное описание ранее упомянутого " _Получения списка контейнеров и отдельного контейнера по ID._". Нет никакого смысла возвращать просто все контейнеры.

> Тут вопрос не в том, что это делает, а в том, что зачем внутри вызова метода определяются две переменные min & max?

Это функция Laravel, это параметры диапазона.

> Не совсем понимаю в чем разница между этими двумя трактовками.

Разница существенна. Ведь если руководствоваться принятой трактовкой термина Уникальный, уникальный товар это тот, который находится в единственном числе. Т.е. если одного и того же товара несколько штук он сразу перестает быть уникальным. А этот факт меняет реализацию.

**Comment by selyakovadim** [comment]
> Нет никакого смысла возвращать просто все контейнеры.

В ТЗ черном по белому написано реализовать этот метод (пункт 2). А уже **на основе этого API** решить задачу. 

> Это функция Laravel, это параметры диапазона.

Наверное правильно будет вызывать метод так?
```php 
$faker->numberBetween(1, 99999999);

**Comment by selyakovadim** [comment]
Тебе же правильно писал @iGusev

> т.е. нужно именно http api дергать, а не в бд ходить. Задача про поиск решения с минимальным количеством проходов по апи

**Comment by skodnik** [comment]
> В ТЗ черном по белому написано реализовать этот метод (пункт 2). А уже на основе этого API решить задачу.

Так именно так я и сделал. Сделал **метод получения списка контейнеров**. А о том, что это за контейнеры написано далее. Ведь слова **всех** в пункте два нет, верно?

> Наверное правильно будет вызывать метод так?

Да, так будет правильнее. Исправлю. Спасибо! Это неудачно перекочевало из моего стартового конфига.

> Тебе же правильно писал @iGusev

Мнение @iGusev основывается на его предположении, вовсе не обязательно (но вполне вероятно) что оно верное. Используемый мной метод может быть использован как для анализа данных из БД, так и для анализа подходящего массива полученного из json. Детали реализации сервиса не декларируются, смею предположить, что их выбор на усмотрение участника.

**Comment by selyakovadim** [comment]
Дружище, я пытаюсь тебе помочь чем могу, а ты все мои слова воспринимаешь в штыки. Дело твоё, конечно. Можешь спорить, а можешь прислушаться. Если тебе два человека говорят, что нужно сделать по-другому и это написано в задаче довольно четко, то может быть так и оно и есть.

**Comment by skodnik** [comment]
Я искренне благодарен помощи, и исправляю замечания. Какие штыки? Наоборот, я крайне рад. Я просто не люблю ставить смайлики :) 

Я еще раз хочу сказать, что у каждого есть свое мнение. И очень здорово, что они иногда отличаются у разных людей. Иначе бы мы все ходили в одинаковой одежде. :D

Спасибо! Я действительно признателен помощи!

**Comment by skodnik** [comment]
> Можешь спорить, а можешь прислушаться.

Наверное даже хорошо, что если я заблуждаюсь, более подходящие (удачливые, умные, сговорчивые и пр.) люди будут в финале, а организаторы не потратят лишних ресурсов. Вместе с тем, если мне удалось прочесть "между строк", и реализовать верно, это будет ценное для всех и во всех смыслах решение.

**Comment by selyakovadim** [comment]
А зачем давать задание, в котором нужно читать что-то между строк? Есть довольно четко поставленная задача, ожидается, что программист эту задачу решит доступными ему средствами. Если мне нужен стул, то я иду к плотнику и прошу его сделать этот стул, он же не будет интерпретировать "между строк" какой мне стул нужен. С четырьмя или тремя ногами.

**Comment by skodnik** [comment]
> А зачем давать задание, в котором нужно читать что-то между строк?

Вполне возможно, что это произошло неумышленно, а может и нет, чего гадать.

> Если мне нужен стул, то я иду к плотнику и прошу его сделать этот стул, он же не будет интерпретировать "между строк" какой мне стул нужен. С четырьмя или тремя ногами.

Стул характеризуется не только количеством ножек, но и массой других свойств которые не очевидны заказчику, но очевидны плотнику. Умный плотник не будет делать стул, который можно купить в Икеа (ведь если бы был нужен стул из Икеа, заказчик там и купил бы) он профессионально оценит ТЗ заказчика иногда даже додумав детали (например, шканты использовать или конфирматы) и сделает стул подходящий именно данному заказчику.

**Comment by selyakovadim** [comment]
> он профессионально оценит ТЗ заказчика иногда даже додумав детали

Окей. Давайте так: есть четыре плотника с 15-летним стажем, они ищут себе подмастерье и чтобы посмотреть на что он способен просят сделать стул. А вместо стула получают табурет.

**Comment by skodnik** [comment]
> есть четыре плотника с 15-летним стажем, они ищут себе подмастерье

На чем основано это предположение? А почему не 4 плотника ищут партнера? :D

Ну и в моем примере заказчик получает не табурет, а заказанный персональный стул, свойства которого превосходят свойства обычного стула.

**Comment by selyakovadim** [comment]
Партнёр, есть новости?

**Comment by selyakovadim** [comment]
@skodnik привет. Есть новости?

**Comment by skodnik** [comment]
@selyakovadim привет. Жду информации. Твое решение оценили?

**Comment by selyakovadim** [comment]
Сегодня пришло письмо, что определили участников. Так что если еще не писали, то скорее всего уже всё.
